name: Update Datasets

on:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: denoland/setup-deno@v2
      - run: deno run --allow-all --unstable-bundle builder/index.ts
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: data
          publish_dir: ./public
